# Generated by Django 2.2.10 on 2020-02-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
