# Generated by Django 3.0.6 on 2020-07-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0004_auto_20200531_1344")]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ("published_date",)}
        )
    ]
