# Generated by Django 2.2.10 on 2020-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.TextField(default='man'),
        ),
    ]
